### PR TITLE
MJAR-263 Add test case for order in jar

### PR DESCRIPTION
**Pull request by schulm**
Added a test for https://github.com/apache/maven-jar-plugin/pull/52.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MJAR) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MJAR-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MJAR-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by schulm** [comment]
@michael-o 
It fails on my mac and on the mac of my colleague. Doesn't fail on my windows machine. 
Hopefully it is reproducible on other macs, too.

**Comment by michael-o** [comment]
Let me try this

**Comment by michael-o** [comment]
Cannot make it fail on UFS and UFS. Asked @cstamas to try. I don't have access to a Max.

**Comment by schulm** [comment]
Regarding the failing test
```
Running post-build script: /home/runner/work/maven-jar-plugin/maven-jar-plugin/target/it/MJAR-263-order-in-jar/verify.groovy
Artifact[en.json] in the wrong order compared to Artifact[it.json]
```
That means that it.json was processed before en.json

**Comment by michael-o** [comment]
This just has been confirmed by @cstamas. `ls -f` shows the FS order. @hboutemy I am still shocked why we have missed this ordering issue...

**Comment by slawekjaranowski** [comment]
confirm failed on:

```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /usr/local/Cellar/maven/3.8.6/libexec
Java version: 11.0.16.1, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@11/11.0.16.1_1/libexec/openjdk.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "12.6", arch: "x86_64", family: "mac"
```

```
ls -f -1 src/it/MJAR-263-order-in-jar/src/main/resources/
.
..
default-configuration.properties
it.json.xml
de.json
excluded-file.txt
en.json
it.json
en.json.xml
fr.json
fr.json.xml
de.json.xml
```

```
unzip -l target/it/MJAR-263-order-in-jar/target/maven-jar-plugin-test-mjar-263-01-99.0.jar 
Archive:  target/it/MJAR-263-order-in-jar/target/maven-jar-plugin-test-mjar-263-01-99.0.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  09-28-2022 15:12   META-INF/
       90  09-28-2022 15:12   META-INF/MANIFEST.MF
        0  09-28-2022 15:12   foo/
        0  09-28-2022 15:12   foo/project003/
        0  09-28-2022 15:12   META-INF/maven/
        0  09-28-2022 15:12   META-INF/maven/org.apache.maven.plugins/
        0  09-28-2022 15:12   META-INF/maven/org.apache.maven.plugins/maven-jar-plugin-test-mjar-263-01/
      785  09-28-2022 15:12   default-configuration.properties
     1014  09-28-2022 15:12   it.json.xml
        6  09-28-2022 15:12   de.json
      875  09-28-2022 15:12   excluded-file.txt
        6  09-28-2022 15:12   en.json
        6  09-28-2022 15:12   it.json
     1014  09-28-2022 15:12   en.json.xml
        6  09-28-2022 15:12   fr.json
      543  09-28-2022 15:12   foo/project003/App.class
     1014  09-28-2022 15:12   fr.json.xml
     1034  09-28-2022 15:12   de.json.xml
     2079  09-28-2022 15:11   META-INF/maven/org.apache.maven.plugins/maven-jar-plugin-test-mjar-263-01/pom.xml
       91  09-28-2022 15:12   META-INF/maven/org.apache.maven.plugins/maven-jar-plugin-test-mjar-263-01/pom.properties

```

**Comment by michael-o** [comment]
OK, this IT is invalid and the issue as well. We do sort and you missed to set `<project.build.outputTimestamp>2019-10-02T08:04:00Z</project.build.outputTimestamp>` in the IT POM. @slawekjaranowski Can you retry with the property?

**Comment by slawekjaranowski** [comment]
With:

```
+
+  <properties>
+    <project.build.outputTimestamp>2019-10-02T08:04:00Z</project.build.outputTimestamp>
+  </properties>
+
```

Pass.

```
unzip -l target/it/MJAR-263-order-in-jar/target/maven-jar-plugin-test-mjar-263-01-99.0.jar 
Archive:  target/it/MJAR-263-order-in-jar/target/maven-jar-plugin-test-mjar-263-01-99.0.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  10-02-2019 08:04   META-INF/
       90  10-02-2019 08:04   META-INF/MANIFEST.MF
        0  10-02-2019 08:04   foo/
        0  10-02-2019 08:04   foo/project003/
        0  10-02-2019 08:04   META-INF/maven/
        0  10-02-2019 08:04   META-INF/maven/org.apache.maven.plugins/
        0  10-02-2019 08:04   META-INF/maven/org.apache.maven.plugins/maven-jar-plugin-test-mjar-263-01/
        6  10-02-2019 08:04   de.json
     1034  10-02-2019 08:04   de.json.xml
      785  10-02-2019 08:04   default-configuration.properties
        6  10-02-2019 08:04   en.json
     1014  10-02-2019 08:04   en.json.xml
      875  10-02-2019 08:04   excluded-file.txt
      543  10-02-2019 08:04   foo/project003/App.class
        6  10-02-2019 08:04   fr.json
     1014  10-02-2019 08:04   fr.json.xml
        6  10-02-2019 08:04   it.json
     1014  10-02-2019 08:04   it.json.xml
     2200  10-02-2019 08:04   META-INF/maven/org.apache.maven.plugins/maven-jar-plugin-test-mjar-263-01/pom.xml
       91  10-02-2019 08:04   META-INF/maven/org.apache.maven.plugins/maven-jar-plugin-test-mjar-263-01/pom.properties
---------                     -------
     8684                     20 files

```

**Comment by schulm** [comment]
Thanks for the help, sorry for startling you...

**Comment by jira-importer** [comment]
Resolve #407

**Pull request closed without merging**
