### PR TITLE
Force alphabetically order in jar archive

### PR DESCRIPTION
**Pull request by schulm**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MJAR) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MJAR-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MJAR-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by schulm** [comment]
@michael-o @hboutemy

I've ran into an issue on my mac, where I migrated a a repository from the maven-bundle-plugin to bnd-maven-plugin and the maven-jar-plugin. The package install failed on my local AEM (Apache Sling) instance. I've investigated this and the root cause was that a file `it.json.xml` was processed before `it.json`.

So I looked at the jar file :

**jar -tf xxx-2.24.0-SNAPSHOT.jar | grep i18**
...
SLING-INF/app-i18n/it.json.xml

SLING-INF/app-i18n/de.json

SLING-INF/app-i18n/en.json

SLING-INF/app-i18n/it.json

SLING-INF/app-i18n/en.json.xml

SLING-INF/app-i18n/fr.json

SLING-INF/app-i18n/fr.json.xml

SLING-INF/app-i18n/de.json.xml
...

And the file `it.json.xml` is clearly added before `it.json`. It currently uses the order from the filesystem (ls -f xxxx.tar shows also that `it.json.xml` is before `it.json`). 

Also this change is one step closer to get fully reproducible builds. (See https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74682318)

**Comment by michael-o** [comment]
We do have this: https://issues.apache.org/jira/browse/MJAR-263

I'd recommend to create a test case w/o any external plugins.

**Comment by schulm** [comment]
In the linked changeset of https://issues.apache.org/jira/browse/MJAR-263, the order of files isn't tackled.

Will hava a look to provide a test case.

**Comment by michael-o** [comment]
Looked up source code. I am quite confused where we do an explicit order...

**Pull request closed without merging**
