### PR TITLE
[MJAR-254] - Fixes filename conflict when producing 2 jars without classifier

### PR DESCRIPTION
**Pull request by Maastiff**
Hello,
I provided a failing test for this issue, I will try to going further to develop the fix.

Done @Hackergarten in Paris with @hboutemy (thanks for his help) ;)

### CODE REVIEW

**Comment by khmarbaise** [comment]
That would be great. I appreciate to see a fix for that and afterwards I appreciate to merge it...

**Comment by rfscholte** [comment]
MJAR-254 is closed as invalid

**Comment by jira-importer** [comment]
Resolve #405

**Comment by jira-importer** [comment]
Resolve #405

**Pull request closed without merging**
