### PR TITLE
[MJAR-269] Add Skip Property to Skip Plugin Execution

### PR DESCRIPTION
**Pull request by brianwyka**
Add the ability to skip plugin execution through pom configuration as well as user property.

**Plugin Configuration example:**
```xml
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-jar-plugin</artifactId>
   <configuration>
       <skip>true</skip>
   </configuration>
</plugin>
```

**Command line example:**
```sh
mvn deploy -Dmaven.jar.skip=true
```

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MJAR) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MJAR-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MJAR-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by brianwyka** [comment]
Added the user property.  Over the weekend, I'll add the pom configuration aspect, and then run the necessary builds and tests.

**Comment by rfscholte** [comment]
As explained in the ticket, I'm not going to accept this PR, the problem needs to be fixed somewhere else.

**Comment by brianwyka** [comment]
@rfscholte, almost every maven plugin has some skip property to allow its execution to be skipped based on the user's discretion.  Why is this plugin any different?

**Comment by jira-importer** [comment]
Resolve #418

**Pull request closed without merging**
